[package]
name = "al-test-derive"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
al-core = { path = "../al-core" }
al-derive = { path = "../al-derive" }
