[package]
name = "al-derive"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
test = false
doctest = false
proc-macro = true

[dependencies]
quote = "1"
syn = "2.0"