[package]
name = "al-transport"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version = "1.80.1"


[dependencies]
al-structures = { path = "../al-structures", features = [
    "noop_waker",
    "enums",
    "race",
    "cancellation",
] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
