[package]
name = "al-net"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lib]
doctest = false

[dependencies]
al-secure = { path = "../al-secure", features = ["noise"] }
al-structures = { path = "../al-structures", features = ["traits", "binary"] }
al-events = { path = "../al-events", features = ["binary"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1", features = ["sync", "net", "time", "io-util"] }

[dev-dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "sync",
    "net",
    "time",
    "io-util",
] }
toml = "0.9.8"
crossterm = "0.29.0"
