[package]
name = "al-math"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { version = "1.25.2", optional = true }
encase = { version = "0.13", optional = true }

[features]
default = ["gpu"]
sdf = []
gpu = ["dep:bytemuck", "dep:encase"]
