[package]
name = "al-math"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"], optional = true }
encase = { version = "0.13", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[features]
default = []
sdf = []
gpu = ["dep:bytemuck", "dep:encase"]
serde = ["dep:serde"]
