[package]
name = "al-structures"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[lib]
doctest = false

[dependencies]
arc-swap = { version = "1.9.1", optional = true }
serde = { version = "1.0.228", features = ["derive"], optional = true }
erased-serde = { version = "0.4.10", optional = true }
serde_json = { version = "1.0.15", optional = true }
al-derive = { path = "../al-derive", optional = true }
tynm = { version = "0.2.0", optional = true }
bitcode = { version = "0.6.9", features = ["serde"], optional = true }
paste = { version = "1.0.15", optional = true }

[features]
default = ["test"]
test = [
    "noop_waker",
    "enums",
    "traits",
    "race",
    "cancellation",
    "collections",
    "serde_format",
    "json",
    "binary",
]
paste = ["dep:paste"]
noop_waker = []
enums = []
traits = ["dep:al-derive", "dep:tynm"]
race = []
cancellation = []
collections = ["dep:arc-swap", "paste"]
serde = ["dep:serde"]
serde_utils = ["serde"]
serde_format = ["dep:erased-serde", "serde_utils"]
json = ["serde_format", "dep:serde_json"]
binary = ["serde_format", "dep:bitcode"]
