name: Shared CI

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: 'main or dev'

env:
  CARGO_TERM_COLOR: always

jobs:
  list-crates:
  runs-on: ubuntu-latest
  outputs:
    crates: ${{ steps.list.outputs.crates }}
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: List crates
      id: list
      run: |
        CRATES=$(cargo metadata --format-version 1 --no-deps | jq -c '[.packages[].name]')
        echo "crates=$CRATES" >> "$GITHUB_OUTPUT"
  
  test-native:
    name: 'Native ${{ matrix.platform.os }} - ${{ matrix.crate }} - ${{ matrix.platform.target }}'
    needs: list-crates
    continue-on-error: true
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
          - { os: macos-latest, target: x86_64-apple-darwin }
        crate: ${{ fromJSON(needs.list-crates.outputs.crates) }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update rustup
      run: rustup update
      
    - name: Add target
      run: rustup target add ${{ matrix.platform.target }}

    - name: Install cargp-hack
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Cache files
      uses: Swatinem/rust-cache@v2

    - name: Test features
      run: cargo hack test -p ${{ matrix.crate }} --feature-powerset --target ${{ matrix.platform.target }}